apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-bff-canary
  namespace: foculist
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "5"
spec:
  rules:
    - host: foculist.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-bff-canary
                port:
                  number: 80
