apiVersion: v1
kind: Secret
metadata:
  name: foculist-runtime
  namespace: foculist
type: Opaque
stringData:
  DB_USERNAME: change-me
  DB_PASSWORD: change-me
  JWT_SECRET: change-me
  JWT_ACCESS_EXPIRATION: "900000"
  JWT_REFRESH_EXPIRATION: "2592000000"
  OAUTH2_SUCCESS_REDIRECT_URL: https://app.foculist.com/login/success
