apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/environment: local
patches:
  - target:
      kind: ConfigMap
      name: foculist-runtime
    path: patch-runtime-configmap.yaml
  - target:
      kind: Ingress
      name: gateway-bff
    path: patch-ingress.yaml
replicas:
  - name: identity-service
    count: 1
  - name: project-service
    count: 1
  - name: planning-service
    count: 1
  - name: calendar-service
    count: 1
  - name: meeting-service
    count: 1
  - name: sync-service
    count: 1
  - name: resource-service
    count: 1
  - name: gateway-bff
    count: 1
